version: '3.8'

networks:
    service-mesh:

services:
    python-api:
        build: ./
        command: python3 -m uvicorn src.api.server:app --host 0.0.0.0 --port 5000 --reload
        ports:
            - 15700:5000
        volumes:
            - ./src:/app/src
        networks:
            service-mesh: